### ISSUE TITLE
StateWorker hangs at first startup

### ISSUE THREAD

**Issue by azunyuuuuuuu** [azunyuuuuuuu/Observatory#4]
Log from the docker container:

```csharp
fail: Observatory.StateWorker.Services.StateCheckService[0]
      An exception in ExecuteStateChecks occured.
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Blazor.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri) in /app/src/StateWorker/Extensions/Blazor/HttpClientJsonExtensions.cs:line 25
   at Observatory.StateWorker.Services.StateCheckService.ExecuteStateChecks() in /app/src/StateWorker/Services/StateCheckService.cs:line 55
```

**Comment by azunyuuuuuuu** [comment]
Restarting the container once and it won't lock up.
